Add getpass for token input
ahnaf-zamil/heater pull request #2
Opened 2021-07-02 04:35 UTC by DevHyperCoder

Related to #1 

Changes:
- Add `ask_token` (getpass helper functions) in ux.py
- Switch out `ask_input` to `ask_token` for bot token input
- Formatted __init__.py and setup.py with `black`

2021-07-02 04:45 UTC, ahnaf-zamil requested changes
In `ux.py`, unlike `ask_input`, your `ask_token` does not have ` >> `. So it would be better to do

```py
return getpass.getpass(message + " >> ")
```

2021-07-02 04:45 UTC, ahnaf-zamil commented on heater/ux.py
> +    return getpass.getpass(message)
Unlike `ask_input`, your `ask_token` does not have ` >> `. So it would be better to do

```py
return getpass.getpass(message + " >> ")
```

2021-07-02 04:57 UTC, DevHyperCoder commented
Could we switch that to f strings instead of appending `" >> "` ?

2021-07-03 05:18 UTC, ahnaf-zamil commented
Not needed, please keep it just as it is.

2021-07-03 05:22 UTC, DevHyperCoder commented
@ahnaf-zamil  please check

2021-07-03 05:29 UTC, ahnaf-zamil approved these changes

2021-07-03 05:29 UTC, merged